CREATE DATABASE MONETIZANDO;


CREATE TABLE TBD_USER (
    ID_USR INT AUTO_INCREMENT,
    NM_USER VARCHAR(100) NOT NULL,
    user VARCHAR (100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);